name: Earthly build
on:
  workflow_dispatch:
  push:
    branches: ['main']
    tags: ['*']
  pull_request:
  schedule:
    - cron: '0 11 * * *'
jobs:
  build-testing-results:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up earthly
        run: |
          sudo wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly
          sudo chmod 755 /usr/local/bin/earthly
      - name: Build Test Space ROS
        id: build
        run: |
          earthly --ci --output +build-test --VCS_REF="$(git rev-parse HEAD)"
      - name: Upload build results archive
        uses: actions/upload-artifact@v3
        with:
          name: build_results.tar.bz2
          path: build_test_results.tar.bz2
          if-no-files-found: error
  space-ros-core-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up earthly
        run: |
          sudo wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly
          sudo chmod 755 /usr/local/bin/earthly
      - name: Build spaceros image
        run: |
          earthly --ci --output +main-image --VCS_REF="$(git rev-parse HEAD)" --SKIP_BUILD_TESTS=true
      # Only push to latest if we are building a release
      - name: Set latest image tag
        id: set_build_tags
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "latest_image_tag=osrf/space-ros:latest" >> $GITHUB_ENV
          fi
        env:
          latest_image_tag: ""
      # Push both tagged releases and the latest main builds to Dockerhub
      - name: Push spaceros images to Dockerhub
        if: ${{ github.ref_type == 'tag' || github.ref_name == 'main' }}
        env:
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_RW_TOKEN }}
          LATEST_IMAGE_TAG: ${{ env.latest_image_tag }}
        run: |
          echo $DOCKER_HUB_TOKEN | docker login --username osrfbot --password-stdin
          earthly --ci --push +push-image --TAG="osrf/space-ros:${{ github.ref_name }}" --LATEST="$LATEST_IMAGE_TAG"
      # Only push the main builds to GHCR
      - name: Push the main spaceros image to GHCR
        if: ${{ github.ref_name == 'main' }}
        run: |
          earthly --ci --push +push-image --TAG="ghcr.io/space-ros/space-ros:${{ github.ref_name }}" --LATEST=""
